export const EVENT_SERVER_COMMAND = {
  GET_EVENTS: 'get-events',
  GET_EVENT_BY_ID: 'get-event-by-id',
  CREATE_EVENT: 'create-event',
  UPDATE_EVENT_ACTIVE: 'update-event-active',
  CLAIM_EVENT_REWARD: 'claim-event-reward',
  CREATE_REWARD_ITEM: 'create-reward-item',
  CREATE_REWARD: 'create-reward',
  GET_REWARD_ITEMS: 'get-reward-items',
  GET_ALL_REWARD_CLAIM_HISTORIES: 'get-all-reward-claim-histories',
  GET_USER_REWARD_CLAIM_HISTORIES: 'get-user-reward-claim-histories',
  GET_ALL_REWARDS: 'get-all-rewards',
  GET_REWARD_BY_ID: 'get-reward-by-id',
  AFTER_USER_CREATED: 'after-user-created',
  AFTER_USER_LOGIN: 'after-user-login',
};
